services:
  - type: web
    name: naghma-mp3
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: OPEN_BROWSER=0 gunicorn -b 0.0.0.0:$PORT --timeout 300 --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OPEN_BROWSER
        value: "0"
